### ISSUE TITLE
Error when installing loadconfig in gitlab CI infrastructure

### ISSUE THREAD

**Issue by AGloberman** [mzdaniel/loadconfig#7]
I'm seeing the following error from my gitlab CI runner after installing the loadconfig package via requirements.txt/setup.py.  Any thoughts on what might be going on?  It doesn't appear to be a regression in the latest release, and I'm not seeing the error when running the build/test commands on my local workstations.

Searching for loadconfig==0.1.1
Reading https://pypi.python.org/simple/loadconfig/
Best match: loadconfig 0.1.1
Downloading https://pypi.python.org/packages/4b/6c/23013b230e759b329fdc88fd6a037963442d203216bbe6cbd134a5a405b0/loadconfig-0.1.1.tar.gz#md5=89460306cf2460991f77def064b7f3ee
Processing loadconfig-0.1.1.tar.gz
Writing /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/setup.cfg
Running loadconfig-0.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/egg-dist-tmp-eKrMec
Searching for pbr
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 1.10.0
Downloading https://pypi.python.org/packages/c3/2c/63275fab26a0fd8cadafca71a3623e4d0f0ee8ed7124a5bb128853d178a7/pbr-1.10.0.tar.gz#md5=8e4968c587268f030e38329feb9c8f17
Processing pbr-1.10.0.tar.gz
Writing /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/temp/easy_install-52dHnx/pbr-1.10.0/setup.cfg
Running pbr-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/temp/easy_install-52dHnx/pbr-1.10.0/egg-dist-tmp-7q7RWm

Installed /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/pbr-0.1.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-vQNzJ3/loadconfig-0.1.1/pbr-0.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-vQNzJ3/loadconfig-0.1.1/pbr-0.1.1-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-vQNzJ3/loadconfig-0.1.1/pbr-0.1.1-py2.7.egg/pbr/util.py", line 310, in setup_cfg_to_setup_kwargs
    description_file = open(filename)
IOError: [Errno 2] No such file or directory: 'README.rst'
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-vQNzJ3/loadconfig-0.1.1/setup.cfg: IOError: [Errno 2] No such file or directory: 'README.rst'

**Comment by mzdaniel** [comment]
It looks like your gitlab CI is running different software versions and posible a different OS.
Try updating your pip in gitlab?

**Comment by AGloberman** [comment]
Quite right!  I updated the version of pip (and setuptools) installed in our build runner containers and things are working once more.  Thanks for the pointer.
